### ISSUE TITLE
Markbot issue

### ISSUE THREAD

**Issue by KimothyPepper** [KimothyPepper/responsive-infographic#2]
<img width="1270" alt="screen shot 2016-02-25 at 12 34 38 pm" src="https://cloud.githubusercontent.com/assets/10464620/13328411/7631b23a-dbbc-11e5-8686-92ad3019be6c.png">

I'm not sure what I'm doing wrong. It looks exactly like Markbot says.

@thomasjbradley

**Comment by thomasjbradley** [comment]
Your code has 2 spaces before the word `width` on that line.
